# Generated by Django 3.2.2 on 2021-05-28 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dummy_app', '0002_auto_20210525_2315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
        migrations.DeleteModel(
            name='register',
        ),
    ]
