# Generated by Django 3.2.2 on 2021-06-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dummy_app', '0005_auto_20210620_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='Bitotsspot',
            field=models.CharField(max_length=5, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='personal',
            name='BloodPressure',
            field=models.IntegerField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='personal',
            name='Breakfast',
            field=models.CharField(max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='personal',
            name='Dinner',
            field=models.CharField(max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='personal',
            name='Glucose',
            field=models.IntegerField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='personal',
            name='Goitre',
            field=models.CharField(max_length=5, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='personal',
            name='Height',
            field=models.IntegerField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='personal',
            name='Lunch',
            field=models.CharField(max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='personal',
            name='Pailor',
            field=models.CharField(max_length=5, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='personal',
            name='Pittingodema',
            field=models.CharField(max_length=5, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='personal',
            name='Snack',
            field=models.CharField(max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='personal',
            name='Weight',
            field=models.IntegerField(null='True'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='personal',
            name='Foodhabit',
            field=models.CharField(max_length=12, null='True'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='Gender',
            field=models.CharField(max_length=12, null='True'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='Worktype',
            field=models.CharField(max_length=12, null='True'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='name',
            field=models.CharField(max_length=100, null='True'),
        ),
    ]
