# Generated by Django 3.2.2 on 2021-06-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dummy_app', '0008_auto_20210621_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='Height',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personal',
            name='Weight',
            field=models.IntegerField(max_length=50),
        ),
    ]
