# Generated by Django 3.2.2 on 2021-06-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dummy_app', '0009_auto_20210621_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='Height',
            field=models.IntegerField(null='True'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='Weight',
            field=models.IntegerField(null='True'),
        ),
    ]
