# Generated by Django 3.2.2 on 2021-06-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dummy_app', '0010_auto_20210621_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nameofthefood', models.CharField(max_length=50)),
                ('Calories', models.CharField(max_length=50)),
                ('Carbs', models.CharField(max_length=50)),
                ('Protein', models.CharField(max_length=50)),
                ('Fat', models.CharField(max_length=50)),
            ],
        ),
    ]
