# Generated by Django 3.2.2 on 2021-07-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dummy_app', '0012_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Phone',
            field=models.IntegerField(),
        ),
    ]
